/**
 * Adaptive HLS master playlists for every site video.
 * Generated by the video-hls plugin into `public/video/hls/<slug>/master.m3u8`.
 * The original .mp4 files remain in `public/video/` as a last-resort fallback.
 */
export const HLS = {
  /** Langzeit-Design film — German narration. */
  langzeitdesignDE: '/video/hls/langzeitdesign/master.m3u8',
  /** Same film — English narration ("Long Term Design"). */
  langzeitdesignEN: '/video/hls/long-term-design-en/master.m3u8',
  sophienkirche: '/video/hls/sophienkirche-prototyp/master.m3u8',
  zpAr: '/video/hls/zp-ar/master.m3u8',
  /** UAV aerial photogrammetry / visualisation clip — German narration. */
  zpUav: '/video/hls/zp-uav/master.m3u8',
  /** Same clip — English narration ("A look into the future …"). */
  zpUavEN: '/video/hls/zp-uav-en/master.m3u8',
} as const

export type Lang = 'de' | 'en'
